class WINDOW:
    WIDTH = 400
    HEIGHT = 600
    SIZE = WIDTH, HEIGHT
    TITLE = "CHATAPP"


class MAINMENU_LAYOUT:
    PADDING = WINDOW.WIDTH * 0.02
    USERNAMES_BUTTON_HEIGHT = WINDOW.HEIGHT * 0.075
    USERNAMES_BUTTON_WIDTH = WINDOW.WIDTH - PADDING * 2


class CHATMENU_LAYOUT:
    TEXTBOX_WIDTH = WINDOW.WIDTH * 2 / 3
    FONT_SIZE = 16


class COLOURS:
    LIGHT_BLACK = (30, 30, 30)
    DARK_GREY = (75, 75, 75)
    LIGHT_GREY = (120, 120, 120)
    GREEN = (0, 255, 0)
    PURPLE = (255, 0, 255)
    WHITE = (255, 255, 255)
    BLACK = (0, 0, 0)


class BUTTON:
    NORMAL_COLOR = COLOURS.DARK_GREY
    HOVER_COLOR = COLOURS.LIGHT_GREY
    TEXT_COLOR = COLOURS.WHITE
